"use client";
import { useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import LegalLayout from "@/components/marketing/LegalLayout";
import { PERMISSION_MATRIX } from "@/lib/roles";

gsap.registerPlugin(ScrollTrigger, useGSAP);

const JOURNEY = [
  { number: "01", title: "Créer l’espace", body: "Connecte-toi avec Google, choisis Patron, puis renseigne le nom et le logo de ton établissement." },
  { number: "02", title: "Préparer le parcours", body: "Repars d’un modèle de formulaire, ajuste les champs, puis crée autant de QR et points d’accueil que nécessaire." },
  { number: "03", title: "Accueillir", body: "Le visiteur scanne, remplit et signe sans compte. La tablette continue de fonctionner même sans réseau." },
  { number: "04", title: "Piloter", body: "Le registre, les statistiques Recharts, les exports et la gestion d’équipe restent disponibles depuis le dashboard." },
];

export default function AidePage() {
  const root = useRef<HTMLDivElement>(null);
  useGSAP(() => {
    gsap.from(".help-hero > *", { y: 24, opacity: 0, duration: 0.7, stagger: 0.1, ease: "power3.out" });
    gsap.from(".help-step", { scrollTrigger: { trigger: ".help-journey", start: "top 78%" }, y: 35, opacity: 0, duration: 0.65, stagger: 0.12, ease: "power3.out" });
    gsap.from(".help-block", { scrollTrigger: { trigger: ".help-block", start: "top 84%" }, x: -24, opacity: 0, duration: 0.7, stagger: 0.1, ease: "power2.out" });
  }, { scope: root });

  return <div ref={root}><LegalLayout title="Aide"><div className="help-hero mb-14 rounded-[1.5rem] bg-mk-deep p-7 text-deep-ink sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.14em] text-mk-sage">Le parcours R3NS3IGN3M3NT</p><h2 className="mt-4 max-w-2xl text-3xl font-bold leading-[0.98] tracking-[-0.03em] text-deep-ink sm:text-5xl">Du premier QR à une arrivée maîtrisée.</h2><p className="mt-5 max-w-xl text-sm font-bold leading-relaxed text-mk-sage">Une aide courte, pensée pour comprendre quoi faire dans le bon ordre — Patron, Gérant, Staff ou visiteur.</p></div>
      <section className="help-journey mb-16 grid gap-3 sm:grid-cols-2"><h2 className="sr-only">Les quatre étapes</h2>{JOURNEY.map((step) => <article key={step.number} className="help-step rounded-2xl border border-mk-ink/10 bg-mk-stone p-6"><span className="text-xs font-bold text-mk-moss">{step.number}</span><h3 className="mt-8 text-xl font-bold">{step.title}</h3><p className="mt-2 text-sm font-bold leading-relaxed text-mk-ink/70">{step.body}</p></article>)}</section>
      <div className="space-y-12"><section className="help-block"><h2>Pour le Patron</h2><h3>Comment créer mon espace ?</h3><p>Clique sur « Se connecter » et utilise ton compte Google. L’onboarding te guide pour choisir ton rôle, renseigner l’établissement, configurer le formulaire et afficher le QR.</p><h3>Comment configurer l’établissement ?</h3><p>Ajoute le nom et le logo grâce au dépôt Cloudinary, puis définis les motifs de visite. Le logo apparaît dans l’interface, le formulaire public et au centre du QR.</p><h3>Comment gérer mon équipe ?</h3><p>Invite un Gérant ou un membre Staff par email. La personne doit se connecter avec le compte Google invité pour être rattachée à l’établissement.</p><h3>À quoi sert le mode Accueil / Staff ?</h3><p>Le Patron ou le Gérant peut ouvrir Dashboard → Accueil lorsqu’aucun membre Staff n’est disponible. Le QR s’affiche en grand et un bouton ouvre directement le formulaire pour une tablette d’accueil.</p><h3>Comment lire les statistiques ?</h3><p>Dashboard → Registre affiche le volume total, le volume du jour, l’heure de pointe, la courbe horaire Recharts et les motifs fréquents. Le registre et les statistiques s’actualisent automatiquement toutes les 30 secondes.</p><h3>Comment récupérer mes données ?</h3><p>Dashboard → Registre → Exporter en CSV.</p></section>
        <section className="help-block"><h2>Pour le Gérant et le Staff</h2><p>Le Gérant peut gérer les opérations autorisées, tandis que le Staff consulte le registre et utilise l’accueil. Les actions sensibles, comme renommer l’établissement, changer le logo, inviter des membres ou régénérer le QR, restent réservées au Patron.</p></section>
        <section className="help-block"><h2>Matrice de permissions</h2><p>Cette matrice indique ce que chaque rôle peut faire dans l’interface. Le Patron correspond au rôle <strong>BOSS</strong>, le Gérant au rôle <strong>GERANT</strong> et le Staff au rôle <strong>STAFF</strong>.</p><div className="mt-5 overflow-x-auto rounded-xl border border-mk-ink/10"><table className="min-w-[640px] w-full border-collapse text-left text-sm"><thead><tr className="border-b border-mk-ink/10 bg-mk-stone"><th className="p-3 font-bold">Action</th><th className="p-3 text-center font-bold">Patron</th><th className="p-3 text-center font-bold">Gérant</th><th className="p-3 text-center font-bold">Staff</th></tr></thead><tbody>{PERMISSION_MATRIX.map((row) => <tr key={row.label} className="border-b border-mk-ink/10 last:border-0"><td className="p-3 text-mk-ink/80">{row.label}</td>{([row.boss, row.gerant, row.staff]).map((allowed, index) => <td key={index} className="p-3 text-center font-bold">{allowed ? <span className="text-mk-moss" aria-label="Oui">Oui</span> : <span className="text-mk-ink/35" aria-label="Non">Non</span>}</td>)}</tr>)}</tbody></table></div></section>
        <section className="help-block"><h2>Règle de sécurité</h2><p>La matrice frontend sert uniquement à afficher ou masquer les actions. La sécurité réelle est appliquée côté API : le Patron a accès aux actions sensibles, le Gérant aux opérations courantes, et le Staff à la consultation et à l’accueil uniquement.</p><p>Un Staff ne peut pas contourner l’interface pour modifier un formulaire ou créer un point d’accueil. Un Gérant peut gérer les formulaires et les points d’accueil, mais ne peut pas supprimer ces ressources, inviter des membres, renommer l’établissement ou régénérer le QR principal. Le Visiteur n’a aucun compte et accède uniquement au formulaire public via un QR actif.</p></section>
        <section className="help-block"><h2>Pour le visiteur</h2><h3>Dois-je créer un compte ?</h3><p>Non. Scanne le QR ou utilise la tablette d’accueil : aucun compte visiteur n’est nécessaire.</p><h3>Et si je n’ai pas de réseau ou de téléphone ?</h3><p>L’établissement peut fournir une tablette. Le formulaire peut conserver les données localement et les synchroniser lorsque l’appareil retrouve Internet.</p><h3>Que devient ma signature ?</h3><p>Elle est enregistrée avec la fiche lorsque le formulaire la demande et reste accessible uniquement aux membres autorisés de l’établissement.</p></section></div><div className="legal-warning">Une question qui ne trouve pas de réponse ici ? <strong>Écris à l’équipe AKATech Studio depuis le widget Feedback.</strong></div>
    </LegalLayout></div>;
}
