# Generated by Django 5.0.6 on 2026-09-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='billing_unit',
            field=models.CharField(blank=True, choices=[('hour', 'Par heure'), ('session', 'Par séance'), ('day', 'Par jour'), ('night', 'Par nuit'), ('month', 'Par mois'), ('fixed', 'Forfait fixe')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, choices=[('accommodation', 'Hébergement'), ('beauty', 'Beauté et soins'), ('workspace', 'Espaces professionnels'), ('events', 'Événementiel et restauration'), ('parking', 'Stationnement'), ('leisure', 'Sport et loisirs'), ('other', 'Autre ressource')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='duration_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
