"use client";
import { useEffect, useState } from "react";
import { Plus, Sparkle, Trash } from "@phosphor-icons/react";
import Loader from "@/components/Loader";
import Modal from "@/components/ui/Modal";
import FormBuilder from "@/components/FormBuilder";
import { apiClient } from "@/lib/api";
import { FORM_PRESETS } from "@/lib/formPresets";
import type { FormField, FormTemplate } from "@/types";

type ViewState = "loading" | "error" | "ready";
const fieldLabels: Record<string, string> = { text: "Texte", phone: "Téléphone", email: "Email", number: "Nombre", date: "Date", select: "Liste", checkbox: "Case", signature: "Signature" };

export default function FormulairePage() {
  const [forms, setForms] = useState<FormTemplate[]>([]);
  const [selected, setSelected] = useState<FormTemplate | null>(null);
  const [state, setState] = useState<ViewState>("loading");
  const [modalOpen, setModalOpen] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [presetId, setPresetId] = useState("vierge");
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState("");
  const load = () => { setState("loading"); apiClient.get<FormTemplate[]>("/form-templates/").then((res) => { setForms(res.data); setSelected((current) => res.data.find((item) => item.id === current?.id) || res.data.find((item) => item.is_default) || res.data[0] || null); setState("ready"); }).catch(() => setState("error")); };
  useEffect(load, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); const preset = FORM_PRESETS.find((item) => item.id === presetId) ?? FORM_PRESETS[0]; if (!newTitle.trim() || !preset) return; setCreating(true); setCreateError(""); try { const response = await apiClient.post<FormTemplate>("/form-templates/", { title: newTitle.trim(), fields_schema: preset.fields, is_default: forms.length === 0, is_active: true }); setForms((items) => [...items, response.data]); setSelected(response.data); setNewTitle(""); setModalOpen(false); } catch { setCreateError("Impossible de créer le formulaire. Réessaie."); } finally { setCreating(false); } };
  const makeDefault = async (form: FormTemplate) => { const response = await apiClient.patch<FormTemplate>(`/form-templates/${form.id}/`, { is_default: true }); setForms((items) => items.map((item) => ({ ...item, is_default: item.id === form.id }))); setSelected(response.data); };
  const remove = async (form: FormTemplate) => { if (!window.confirm(`Supprimer « ${form.title} » ?`)) return; await apiClient.delete(`/form-templates/${form.id}/`); load(); };
  if (state === "loading") return <Loader fullScreen={false} />;
  if (state === "error") return <div className="space-y-3"><p className="text-ink-soft">Impossible de charger les formulaires.</p><button onClick={load} className="rounded-full bg-cta px-4 py-2 text-sm text-white">Réessayer</button></div>;
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-ink-soft">Parcours visiteurs</p><h1 className="mt-1 text-2xl font-bold text-ink">Formulaires</h1><p className="mt-1 max-w-2xl text-sm text-ink-soft">Un formulaire suffit pour commencer. Crée ensuite un autre parcours uniquement quand tu en as besoin.</p></div><button onClick={() => { setModalOpen(true); setCreateError(""); }} className="flex items-center gap-2 rounded-full bg-cta px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17} weight="bold" /> Nouveau formulaire</button></div>
    <div className="grid gap-3 md:grid-cols-2">{forms.map((form) => <div key={form.id} className={`rounded-xl border p-4 transition ${selected?.id === form.id ? "border-ink bg-surface shadow-subtle" : "border-border bg-canvas"}`}><button onClick={() => setSelected(form)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><p className="font-semibold text-ink">{form.title}</p>{form.is_default && <span className="rounded-full bg-success-bg px-2 py-1 text-[11px] font-semibold text-success-text">Par défaut</span>}</div><p className="mt-1 text-xs text-ink-soft">{form.fields_schema.length} champs · version {form.version}</p><div className="mt-3 flex flex-wrap gap-1.5">{form.fields_schema.slice(0, 5).map((field: FormField) => <span key={field.id} className="rounded bg-canvas px-2 py-1 text-[11px] text-ink-soft">{fieldLabels[field.type] || field.type}</span>)}</div></button><div className="mt-4 flex items-center gap-4 border-t border-border pt-3 text-xs"><button onClick={() => makeDefault(form)} className="text-ink-soft hover:underline">Utiliser par défaut</button><button onClick={() => remove(form)} className="flex items-center gap-1 text-error-text hover:underline"><Trash size={14} /> Supprimer</button></div></div>)}</div>
    {selected && <div className="rounded-2xl border border-border bg-surface p-5"><div className="mb-5 flex items-center gap-2"><Sparkle size={19} className="text-ink-soft" /><div><h2 className="font-heading font-semibold text-ink">Modifier « {selected.title} »</h2><p className="text-sm text-ink-soft">Choisis un modèle ou ajuste chaque champ avant de déployer.</p></div></div><FormBuilder key={selected.id} formId={selected.id} initialTitle={selected.title} initialSchema={selected.fields_schema as FormField[]} onSaved={load} /></div>}
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Créer un formulaire" description="Pars d’un modèle, puis personnalise ses champs dans l’éditeur." wide><form onSubmit={create} className="space-y-5"><div><label className="mb-1.5 block text-sm font-medium text-ink">Nom du formulaire</label><input autoFocus required value={newTitle} onChange={(e) => setNewTitle(e.target.value)} placeholder="Ex. Visiteurs siège, Livraisons, Événements" className="w-full rounded-lg border border-border bg-canvas px-3 py-3 text-sm text-ink outline-none focus:border-ink" /></div><div><label className="mb-2 block text-sm font-medium text-ink">Repartir d’un modèle</label><div className="grid gap-2 sm:grid-cols-2">{FORM_PRESETS.map((preset) => <label key={preset.id} className={`cursor-pointer rounded-xl border p-3 transition ${presetId === preset.id ? "border-ink bg-canvas" : "border-border"}`}><input type="radio" name="preset" value={preset.id} checked={presetId === preset.id} onChange={() => setPresetId(preset.id)} className="sr-only" /><span className="font-medium text-ink">{preset.label}</span><span className="mt-1 block text-xs text-ink-soft">{preset.fields.length} champs · {Array.from(new Set(preset.fields.map((field) => fieldLabels[field.type] || field.type))).join(" · ")}</span></label>)}</div></div>{createError && <p className="text-sm text-error-text">{createError}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={() => setModalOpen(false)} className="rounded-full border border-border px-4 py-2.5 text-sm text-ink">Annuler</button><button disabled={creating} className="rounded-full bg-cta px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{creating ? "Création…" : "Créer et personnaliser"}</button></div></form></Modal>
  </div>;
}
