# Generated by Django 5.0.6 on 2026-09-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedback_fe_status_212662_idx',
            old_name='feedback_st_status_8d1d5b_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedback_fe_organiz_298d02_idx',
            old_name='feedback_st_organiz_3fa4e5_idx',
        ),
    ]
