# Generated by Django 5.0.6 on 2026-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('BOSS', 'Patron'), ('GERANT', 'Gérant'), ('STAFF', 'Agent')], default='STAFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BOSS', 'Patron'), ('GERANT', 'Gérant'), ('STAFF', 'Agent')], default='BOSS', max_length=10),
        ),
    ]
