# Generated by Django 5.0.6 on 2026-09-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staffinvitation_role_alter_user_role'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS avatar_url text DEFAULT '';",
                    reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS avatar_url;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='avatar_url',
                    field=models.TextField(blank=True),
                ),
            ],
        ),
    ]

