# Generated by Django 5.0.6 on 2026-09-23 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_refreshsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'GERANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
