# Generated by Django 5.0.6 on 2026-09-14 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default="Registre d'accès", max_length=255)),
                ('fields_schema', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_template', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('responses', models.JSONField(default=dict)),
                ('signature_blob', models.TextField(blank=True, null=True)),
                ('created_at_client', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='organizations.organization')),
                ('form_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkins.formtemplate')),
            ],
            options={
                'ordering': ['-created_at_client'],
                'indexes': [models.Index(fields=['organization', '-created_at_client'], name='checkins_ch_organiz_2174e4_idx')],
            },
        ),
    ]
