# Generated by Django 5.0.6 on 2026-09-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_multiform_access_points'),
        ('organizations', '0002_organization_branding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['access_point', '-created_at_client'], name='checkins_ch_access__d99239_idx'),
        ),
    ]
