# Generated by Django 5.0.6 on 2026-09-26
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checkins", "0003_checkin_checkins_ch_access__d99239_idx"),
        ("karnet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkins",
                to="karnet.client",
            ),
        ),
    ]
